name: Advanced Usage

on: push

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean Documentation Dist Folder
        run: |
          rm -rf docs/dist
          mkdir docs/dist

      - name: DocGen - Programming Documentation
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/result.pdf "docs/src/documentation.md"

      - name: Upload Generated Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/dist/*
