name: Documentation Release

on:
  push:
    branches: [ "main" ]
    paths: ['docs/src/**']
  pull_request:
    branches: [ "main" ]
    paths: ['docs/src/**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Documentation via Pandoc/Extra Container
        uses: docker://pandoc/extra:latest
        with:
          args: "docs/src/testing.md -o docs/dist/testing.pdf --template eisvogel --listings"
