name: Documentation Release

on:
  push:
    branches: [ "main" ]
    paths: ['docs/src/**']
  pull_request:
    branches: [ "main" ]
    paths: ['docs/src/**']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Run
        run: docker run -it --rm mbentley/cowsay holy ship!
