name: Advanced Usage

on: push

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Documentation Filepaths
        id: files_list
        run: |
          rm -rf docs/dist
          mkdir docs/dist
          cd docs/src
          echo "files=$(printf '"docs/src/%s" ' *.md)" > $GITHUB_OUTPUT
          cd ../..

      - name: Generate Documentation PDFs
        uses: docker://pandoc/extra:latest
        with:
          args: --listings --template https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex --output=docs/dist/result.pdf ${{ steps.files_list.outputs.files }}

      - name: Upload Generated Documentation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/dist/*
